DELIMITER $$
CREATE PROCEDURE PA_INSERTAR_NOTRANSACCIONAL ( 
    in PIDCUENTAORIGEN int, 
    in PIDCUENTADESTINO int, 
    in PVALOR numeric(10,2))
BEGIN
    
    START TRANSACTION;
    insert into TRANSFERENCIA values(PIDCUENTAORIGEN, PIDCUENTADESTINO, PVALOR);
    insert into MOVIMIENTO(IDCUENTA,TIPOMOVIMIENTO,VALOR) values(PIDCUENTADESTINO, 'A', PVALOR);
    update CUENTA set SALDO=saldo+ PVALOR where IDCUENTA = PIDCUENTADESTINO ;
    insert into MOVIMIENTO(IDCUENTA,TIPOMOVIMIENTO,VALOR) values(PIDCUENTAORIGEN, 'D', PVALOR);
    update CUENTA set SALDO = saldo - PVALOR where IDCUENTA = PIDCUENTAORIGEN;
    
END$$
DELIMITER ;
